### ISSUE TITLE
Unable to set second path as a source

### ISSUE THREAD

**Issue by gottspeed** [noinip/cherrymusic#1]
Hi pinion, I'd like to have cherrymusic draw upon multiple directories but I don't see a way to do that. Is it possible?

**Comment by noinip** [comment]
That's a good question. According to the CherryMusic wiki you should do a symbolic link:
https://github.com/devsnd/cherrymusic/wiki/Setup-guide#tips-and-tricks

That said I just tried that on my unraid server and it didn't work. After some more research it appears Docker does not handle symlinks well at all or at least directories that contain symlinked directories. Also, I'm not sure their solution would work as well in Windows. My suggestion would be to put all of your music under one directory such as /mnt/user/Media/Music.

Thank you very much for the question. I haven't been using CherryMusic for a while and it looks like it recently got an updat after over 2 years. Additionally, it also looks like my docker container for it has been getting some attention lately so I'm motivated to clean it up and do some updating. If you run across anything about symbolic links in Docker that I missed please reopen this and I'll take a look.
